Feature/test ng annotation test
Olehqa/automation-framework pull request #6
Opened 2020-11-18 10:30 UTC by Olehqa

2020-11-18 10:46 UTC, iikarak requested changes

2020-11-18 10:46 UTC, iikarak commented on src/main/resources/suite.xml
> +       allow-return-values="true" verbose="1"
explain meaning  of 'verbose', ' allow-return-values'

2020-11-18 10:46 UTC, iikarak commented on src/main/resources/suite.xml
> +    <test name="all" parallel="classes" thread-count="5" time-out="240000">
to tell me a story

2020-11-18 10:46 UTC, iikarak commented on src/test/java/com/aramework/learn/automation/firsttests/AllTestNgAnnotationsTest.java
> +    @Test(description = "First Test", dependsOnGroups = "group1")
dependsOnGroups  vs dependsOnMethod

2020-11-18 10:46 UTC, iikarak commented on src/test/java/com/aramework/learn/automation/firsttests/AllTestNgAnnotationsTest.java
> +    @Test(description = "First Test", dependsOnGroups = "group1")
dependsOnGroups user for test methods and beforeSuite and beforeTest so on .

when you would like to have dependency beetween before-any

2020-12-01 11:09 UTC, iikarak requested changes

2020-12-01 11:09 UTC, iikarak commented on src/test/java/com/framework/learn/automation/firsttests/AllTestNgAnnotationsTest.java
> +    @BeforeGroups(description = "group of tests", groups = "group")
depends on group, in group several tests, what will be order of execution

2020-12-15 10:40 UTC, iikarak requested changes

2020-12-15 10:40 UTC, iikarak commented on pom.xml
> +                        <suiteXmlFile>src/main/resources/suite.xml</suiteXmlFile>
with out full path

2020-12-15 10:40 UTC, iikarak commented on src/main/resources/suite.xml
> +    <test name="all" parallel="classes" thread-count="5" time-out="240000">
Test will fail if toimeout timne will end, so try to test with 1 second, for example

2020-12-15 10:40 UTC, iikarak commented on src/test/java/com/framework/learn/automation/firsttests/AllTestNgAnnotationsTest.java
> +    @Parameters({"parameterFromXml"})
add default value for parameter, in case if parameter is missed

2020-12-15 10:40 UTC, iikarak commented on src/test/java/com/framework/learn/automation/firsttests/AllTestNgAnnotationsTest.java
> +    public Iterator<Object[]> buttonProvider() {
what can be return type here? in data provider 
[][] try with matrix 
to return two value for tests, not one

2020-12-15 10:40 UTC, iikarak commented on src/test/java/com/framework/learn/automation/firsttests/AllTestNgAnnotationsTest.java
> +    public void cleanCookie() {
Move all general functions in Base test class

2021-01-08 14:25 UTC, closed without merging

2021-01-08 14:25 UTC, Olehqa commented
Moved to another learning project